tests: Skip some tests on non-MPTCP kernels.
The mptcpd unit tests test-commands, test-path-manager and
test-mptcpwrap require a MPTCP capable kernel to run.  Make those
tests return with an exit status (77) that causes the Automake test
driver script, i.e. `test-driver' to treat the tests as skipped.  This
allows the test suite to succeed when MPTCP is not available in the
kernel.

The test summary from a `make check' run would look similar to the
following when run on a non-MPTCP capable kernel:

 ...
 PASS: test-network-monitor
 SKIP: test-path-manager
 SKIP: test-commands
 PASS: test-configuration
 ...
 SKIP: test-mptcpwrap
 =========================================================================
 Testsuite summary for mptcpd 0.9
 =========================================================================
 # TOTAL: 17
 # PASS:  14
 # SKIP:  3
 # XFAIL: 0
 # FAIL:  0
 # XPASS: 0
 # ERROR: 0
 =========================================================================

Fixes #204.

diff --git a/tests/test-mptcpwrap b/tests/test-mptcpwrap
--- a/tests/test-mptcpwrap
+++ b/tests/test-mptcpwrap
@@ -7,15 +7,18 @@
 
 set -e
 
+# An exit status of 77 causes the Automake test driver to consider the
+# test as skipped.
+skip_exit_status=77
+
 # Check if we're using the upstream kernel.
 #
-# upstream:          net.mptcp.enabled
-# multipath-tcp.org: net.mptcp.mptcp_enabled
-key=`sysctl --names --pattern 'mptcp\.enabled' net.mptcp`
-if [ -z "$key" ]; then
-    # Do not run the test if we're not using the upstream kernel.
+# upstream:          /proc/sys/net/mptcp/enabled
+# multipath-tcp.org: /proc/sys/net/mptcp/mptcp_enabled
+if [ ! -f /proc/sys/net/mptcp/enabled ]; then
+    # Skip the test if we're not using the upstream kernel.
     echo Not running upstream kernel.  libmptcpwrap will not be tested.
-    exit 0
+    exit $skip_exit_status
 fi
 
 LD_PRELOAD=../src/.libs/libmptcpwrap.so \
