tests: Correct test script failure/exit logic.

diff --git a/tests/test-start-stop b/tests/test-start-stop
--- a/tests/test-start-stop
+++ b/tests/test-start-stop
@@ -10,8 +10,6 @@ echo Running non-interactive sudo check...
 sudo -n echo "    succeeded"
 sudo_exit_code=$?
 
-set -e
-
 variable=`sysctl net.mptcp | grep enabled | sed -e 's/\(net.mptcp.*enabled\).*$/\1/'`
 old_value=`sysctl $variable | sed -e 's/.*= \(.*\)$/\1/'`
 
@@ -35,6 +33,8 @@ command="timeout --preserve-status \
                  --kill-after=5s   \
                  1s ../src/mptcpd --plugin-dir=$TEST_PLUGIN_DIR"
 
+# Exit status/code
+status=0
 
 # Only run the individual enabled/disabled MPTCP test cases if the
 # "enabled" value can be set non-interactively, i.e. sudo can be
@@ -44,15 +44,29 @@ if [ $sudo_exit_code -eq 0 ]
 then
     for value in $disable_value $enable_value
     do
-	echo "TEST CASE: $variable = $value"
-	sudo -n sysctl -w $variable=$value
+	sudo -n sysctl -qw $variable=$value
+
 	$command
+	command_exit=$?
+
+	echo -n "TEST CASE: $variable = $value ..."
+
+	if ([ $value -eq $disable_value ] && [ $command_exit -eq 0 ]) \
+	   || ([ $value -eq $enable_value ] && [ $command_exit -ne 0 ])
+	then
+	    echo failed
+	    status=1   # failure
+	else
+	    echo passed
+	fi
     done
 
     # Reset the "enabled" value to its original value.
-    sudo -n sysctl -w $variable=$old_value
+    sudo -n sysctl -qw $variable=$old_value
 else
     # Non-root case.
     echo Running test without root privileges
     $command
 fi
+
+exit $status
